{
 "title": "Base-Op-Node",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_start_time_seconds{job=\"base-op-node\"}) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "L2 Unsafe Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l2\", type=\"l2_unsafe\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Safe Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l2\", type=\"l2_safe\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Finalized Block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l2\", type=\"l2_finalized\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_node_default_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Block Timestamps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "op_node_default_refs_time * 1000",
     "legendFormat": "{{layer}}: {{type}}"
    }
   ]
  },
  {
   "title": "Block Latencies",
   "type": "timeseries",
   "description": "The difference between the block timestamp + timestamp when the metric was recorded.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "op_node_default_refs_latency * -1",
     "legendFormat": "{{layer}}: {{type}}"
    }
   ]
  },
  {
   "title": "Derivation Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "increase(op_node_default_events_processed[$__rate_interval])",
     "legendFormat": "deriver={{deriver}}, event_type={{event_type}}"
    }
   ]
  },
  {
   "title": "Derivation Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "op_node_default_derivation_errors_total",
     "legendFormat": "Derivation Errors"
    },
    {
     "expr": "op_node_default_channel_timeout_total",
     "legendFormat": "Channel Timeouts"
    },
    {
     "expr": "op_node_default_pipeline_resets_total",
     "legendFormat": "Pipeline Resets"
    }
   ]
  },
  {
   "title": "L1 Reorg Depths",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(op_node_default_l1_reorg_depth_bucket[$__rate_interval])))",
     "legendFormat": "L1 Reorg Depth"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "RPC Client Requests Count Per Time Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(op_node_default_rpc_client_requests_total[$__rate_interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC Client Response Count Per Time Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_rpc_client_responses_total[$__rate_interval])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "RPC Client Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(method, le) (rate(op_node_default_rpc_client_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "P2P Outgoing Dials Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(op_node_default_p2p_dials{allow=\"true\"}[$__interval])",
     "legendFormat": "Accepted"
    },
    {
     "expr": "op_node_default_p2p_dials{allow=\"false\"}",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "P2P Incoming Dials Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(op_node_default_p2p_accepts{allow=\"true\"}[$__interval])",
     "legendFormat": "Accepted"
    },
    {
     "expr": "irate(op_node_default_p2p_accepts{allow=\"false\"}[$__interval])",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Total Received P2P Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by(p2p_method) (rate(op_node_default_p2p_req_total[$__rate_interval]))",
     "legendFormat": "{{p2p_method}}"
    }
   ]
  },
  {
   "title": "Total Received P2P Requests Per Time Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum by(p2p_method) (increase(op_node_default_p2p_req_total[$__rate_interval]))",
     "legendFormat": "{{p2p_method}}"
    }
   ]
  },
  {
   "title": "P2P Bandwidth Increase Per Time Interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(direction) (increase(op_node_default_p2p_bandwidth_bytes_total[$__rate_interval]))",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "P2P Bandwidth Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(op_node_default_p2p_bandwidth_bytes_total[$__interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    { "expr": "op_node_default_p2p_peer_count", "legendFormat": "Peers" }
   ]
  },
  {
   "title": "Peer Score Updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, type) (rate(op_node_default_peer_scores_bucket{type!=\"total\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Requests Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(op_node_default_p2p_req_duration_seconds_bucket{p2p_role=\"server\"}[$__rate_interval])) by (le, p2p_method))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Average Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(p2p_method, p2p_role) (rate(op_node_default_p2p_req_duration_seconds_sum[1h])) / sum by(p2p_role, p2p_method) (rate(op_node_default_p2p_req_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{p2p_role}}: {{p2p_method}}"
    }
   ]
  },
  {
   "title": "P2P Gossip Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(op_node_default_p2p_gossip_events_total{type!~\"RECV_RPC|SEND_RPC\"}[$__interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Resident Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"base-op-node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}