{
 "title": "Base-Geth",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "geth_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Head Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_block", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Finalized Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_head_finalized", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "p2p_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reorgs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_reorg_executes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Growth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "eth_db_chaindata_disk_size", "legendFormat": "Size ({{job}})" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "system_memory_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Downloader: Bodies Received",
   "type": "timeseries",
   "description": "The number of bodies downloaded, and the rate per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "eth_downloader_bodies_in", "legendFormat": "Downloaded" },
    {
     "expr": "rate(eth_downloader_bodies_in[$__rate_interval])",
     "legendFormat": "Downloaded/s"
    }
   ]
  },
  {
   "title": "Downloader: Headers Received",
   "type": "timeseries",
   "description": "The number of headers downloaded, and the rate per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "eth_downloader_headers_in", "legendFormat": "Downloaded" },
    {
     "expr": "rate(eth_downloader_headers_in[$__rate_interval])",
     "legendFormat": "Downloaded/s"
    }
   ]
  },
  {
   "title": "RPC Response Times By Method (75th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rpc_duration_engine_forkchoiceUpdatedV3_success{quantile=\"0.75\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rpc_duration_engine_newPayloadV3_success{quantile=\"0.75\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rpc_duration_engine_signalSuperchainV1_success{quantile=\"0.75\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rpc_duration_eth_chainId_success{quantile=\"0.75\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rpc_duration_eth_getBlockByHash_success{quantile=\"0.75\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rpc_duration_eth_getBlockByNumber_success{quantile=\"0.75\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(rpc_requests[10m])", "legendFormat": "Total" },
    { "expr": "rate(rpc_success[10m])", "legendFormat": "Successful" },
    { "expr": "rate(rpc_failure[10m])", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "RPC Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rpc_duration_all{quantile=\"0.75\"}",
     "legendFormat": "75% Quantile"
    },
    {
     "expr": "rpc_duration_all{quantile=\"0.95\"}",
     "legendFormat": "95% Quantile"
    }
   ]
  },
  {
   "title": "RPC Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    { "expr": "rate(rpc_requests[10m])", "legendFormat": "Requests per Second" }
   ]
  },
  {
   "title": "P2P Message Bandwidth (10m Change)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "increase(p2p_egress[10m])", "legendFormat": "Egress" },
    { "expr": "increase(p2p_ingress[10m])", "legendFormat": "Ingress" }
   ]
  },
  {
   "title": "P2P Message Bandwidth Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "rate(p2p_egress[10m])", "legendFormat": "Egress" },
    { "expr": "rate(p2p_ingress[10m])", "legendFormat": "Ingress" }
   ]
  },
  {
   "title": "P2P Egress Message Size (Snap Protocol)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(p2p_egress_snap_1_0x00[$__interval])",
     "legendFormat": "GetAccountRange (0x00)"
    },
    {
     "expr": "irate(p2p_egress_snap_1_0x02[$__interval])",
     "legendFormat": "GetStorageRanges (0x02)"
    },
    {
     "expr": "irate(p2p_egress_snap_1_0x04[$__interval])",
     "legendFormat": "GetBytecodes (0x04)"
    },
    {
     "expr": "irate(p2p_egress_snap_1_0x06[$__interval])",
     "legendFormat": "GetTrieNodes (0x06)"
    }
   ]
  },
  {
   "title": "P2P Ingress Message Size (Snap Protocol)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(p2p_ingress_snap_1_0x01[$__interval])",
     "legendFormat": "AccountRanges (0x01)"
    },
    {
     "expr": "irate(p2p_ingress_snap_1_0x03[$__interval])",
     "legendFormat": "StorageRanges (0x03)"
    },
    {
     "expr": "irate(p2p_ingress_snap_1_0x05[$__interval])",
     "legendFormat": "Bytecodes (0x05)"
    },
    {
     "expr": "irate(p2p_ingress_snap_1_0x07[$__interval])",
     "legendFormat": "TrieNodes (0x07)"
    }
   ]
  },
  {
   "title": "P2P Egress Message Size (Eth Protocol)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(p2p_egress_eth_68_0x00[5m])",
     "legendFormat": "Status (0x00)"
    },
    {
     "expr": "rate(p2p_egress_eth_68_0x03[5m])",
     "legendFormat": "GetBlockHeaders (0x03)"
    },
    {
     "expr": "rate(p2p_egress_eth_68_0x04[5m])",
     "legendFormat": "BlockHeaders (0x04)"
    },
    {
     "expr": "rate(p2p_egress_eth_68_0x05[5m])",
     "legendFormat": "GetBlockBodies (0x05)"
    },
    {
     "expr": "rate(p2p_egress_eth_68_0x0f[5m])",
     "legendFormat": "GetReceipts (0x0f)"
    }
   ]
  },
  {
   "title": "P2P Ingress Message Size (Eth Protocol)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress_eth_68_0x00[5m])",
     "legendFormat": "Status (0x00)"
    },
    {
     "expr": "rate(p2p_ingress_eth_68_0x02[5m])",
     "legendFormat": "Transactions (0x02)"
    },
    {
     "expr": "rate(p2p_ingress_eth_68_0x03[5m])",
     "legendFormat": "GetBlockHeaders (0x03)"
    },
    {
     "expr": "rate(p2p_ingress_eth_68_0x04[5m])",
     "legendFormat": "BlockHeaders (0x04)"
    },
    {
     "expr": "rate(p2p_ingress_eth_68_0x06[5m])",
     "legendFormat": "BlockBodies (0x06)"
    },
    {
     "expr": "rate(p2p_ingress_eth_68_0x08[5m])",
     "legendFormat": "NewPooledTransactionHashes (0x08)"
    },
    {
     "expr": "rate(p2p_ingress_eth_68_0x10[5m])",
     "legendFormat": "Receipts (0x10)"
    }
   ]
  },
  {
   "title": "P2P: Eth Protocol Handshake Errors (Ingress)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_forkid[5m])",
     "legendFormat": "Invalid ForkID"
    },
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_genesis[5m])",
     "legendFormat": "Invalid Genesis"
    },
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_network[5m])",
     "legendFormat": "Invalid Network"
    },
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_peer[5m])",
     "legendFormat": "Invalid Peer Behavior"
    },
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_timeout[5m])",
     "legendFormat": "Timeout"
    },
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_version[5m])",
     "legendFormat": "Invalid Protocol Version"
    }
   ]
  },
  {
   "title": "P2P: Eth Protocol Handshake Errors (Egress)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_forkid[5m])",
     "legendFormat": "Invalid ForkID"
    },
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_genesis[5m])",
     "legendFormat": "Invalid Genesis"
    },
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_network[5m])",
     "legendFormat": "Invalid Network"
    },
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_peer[5m])",
     "legendFormat": "Invalid Peer Behavior"
    },
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_timeout[5m])",
     "legendFormat": "Timeout"
    },
    {
     "expr": "rate(eth_protocols_eth_egress_handshake_error_version[5m])",
     "legendFormat": "Invalid Protocol Version"
    }
   ]
  },
  {
   "title": "Discovery Egress (Packets sent)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "rate(discover_egress[5m])", "legendFormat": "Total bytes sent" }
   ]
  },
  {
   "title": "Discovery Ingress (Packets received)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "rate(discover_ingress[5m])", "legendFormat": "Total bytes received" }
   ]
  },
  {
   "title": "P2P Dial Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(p2p_dials_error_connection[5m])",
     "legendFormat": "Connection Error/s"
    },
    {
     "expr": "rate(p2p_dials_error_id_unexpected[5m])",
     "legendFormat": "Unexpected Dials/s"
    },
    {
     "expr": "rate(p2p_dials_error_known[5m])",
     "legendFormat": "Known Peer/s"
    },
    {
     "expr": "rate(p2p_dials_error_rlpx_enc[5m])",
     "legendFormat": "Invalid RLP Encoding/s"
    },
    {
     "expr": "rate(p2p_dials_error_rlpx_proto[5m])",
     "legendFormat": "Invalid RLP Proto/s"
    },
    {
     "expr": "rate(p2p_dials_error_saturated[5m])",
     "legendFormat": "Too Many Peers/s"
    },
    { "expr": "rate(p2p_dials_error_self[5m])", "legendFormat": "Dialed Self/s" },
    {
     "expr": "rate(p2p_dials_error_useless[5m])",
     "legendFormat": "Useless Peer/s"
    }
   ]
  },
  {
   "title": "Successful Dials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    { "expr": "p2p_dials_success", "legendFormat": "Total" },
    { "expr": "rate(p2p_dials[10m])", "legendFormat": "Successful dials/s" }
   ]
  }
 ]
}