consensus:
  enabled: true
  url: "http://host.docker.internal:5052"
  name: "consensus-client"
execution:
  enabled: true
  url: "http://host.docker.internal:8545"
  name: "execution-client"
  modules:
    - "eth"
    - "net"
    - "web3"